# CalculiX adapter
[[imports]]
path = "github.com/precice/calculix-adapter"

  [[imports.mounts]]
  source = "docs/adapter-calculix-overview.md"
  target = "content/docs/adapters/calculix/_index.md"

  [[imports.mounts]]
  source = "docs"
  target = "content/docs/adapters/calculix"
  files = ["! adapter-calculix-overview.md"]

# code_aster adapter
[[imports]]
path = "github.com/precice/code_aster-adapter"

  [[imports.mounts]]
  source = "docs/adapter-code_aster.md"
  target = "content/docs/adapters/code_aster/_index.md"

  [[imports.mounts]]
  source = "docs/images"
  target = "content/docs/adapters/code_aster/images"

# deal.II adapter
[[imports]]
path = "github.com/precice/dealii-adapter"

  [[imports.mounts]]
  source = "docs/overview.md"
  target = "content/docs/adapters/dealii/_index.md"

  [[imports.mounts]]
  source = "docs"
  target = "content/docs/adapters/dealii"
  files = ["! overview.md"]

# DuMuX adapter
[[imports]]
path = "github.com/precice/dumux-adapter"

  [[imports.mounts]]
  source = "docs/overview.md"
  target = "content/docs/adapters/dumux/_index.md"

  [[imports.mounts]]
  source = "docs"
  target = "content/docs/adapters/dumux"
  files = ["! overview.md"]

# DUNE adapter
[[imports]]
path = "github.com/precice/dune-adapter"

  [[imports.mounts]]
  source = "docs/overview.md"
  target = "content/docs/adapters/dune/_index.md"

# FEniCS adapter
[[imports]]
path = "github.com/precice/fenics-adapter"

  [[imports.mounts]]
  source = "docs/adapter-fenics.md"
  target = "content/docs/adapters/fenics/_index.md"

  [[imports.mounts]]
  source = "docs"
  target = "content/docs/adapters/fenics"
  files = ["! adapter-fenics.md", "! ReleaseGuide.md"]

# FEniCSx adapter
[[imports]]
path = "github.com/precice/fenicsx-adapter"

  [[imports.mounts]]
  source = "docs/README.md"
  target = "content/docs/adapters/fenicsx/_index.md"

# OpenFOAM adapter
[[imports]]
path = "github.com/precice/openfoam-adapter"

  [[imports.mounts]]
  source = "docs/README.md"
  target = "content/docs/adapters/openfoam/_index.md"

  [[imports.mounts]]
  source = "docs"
  target = "content/docs/adapters/openfoam"
  files = ["! README.md", "! images/docs-adapter-openfoam-implicit-loop-src.md"]

# SU2 adapter
[[imports]]
path = "github.com/precice/su2-adapter"

  [[imports.mounts]]
  source = "docs/overview.md"
  target = "content/docs/adapters/su2/_index.md"

  [[imports.mounts]]
  source = "docs"
  target = "content/docs/adapters/su2"
  files = ["! overview.md"]

# ASTE
[[imports]]
path = "github.com/precice/aste"

  [[imports.mounts]]
  source = "docs/README.md"
  target = "content/docs/tooling/aste/_index.md"

# FMI runner
[[imports]]
path = "github.com/precice/fmi-runner"

  [[imports.mounts]]
  source = "docs/README.md"
  target = "content/docs/tooling/fmi-runner/_index.md"

  [[imports.mounts]]
  source = "docs/images"
  target = "content/docs/tooling/fmi-runner/images"

# Micro Manager
[[imports]]
path = "github.com/precice/micro-manager"

  [[imports.mounts]]
  source = "docs/README.md"
  target = "content/docs/tooling/micro-manager/_index.md"

  [[imports.mounts]]
  source = "docs"
  target = "content/docs/tooling/micro-manager"
  files = ["! README.md", "! ReleaseGuide.md"]

# preECO guidelines
[[imports]]
path = "github.com/precice/preeco-orga"

  [[imports.mounts]]
  source = "guidelines/guidelines-adapters.md"
  target = "content/community/contribute/guidelines/_index.md"

  [[imports.mounts]]
  source = "guidelines"
  target = "content/community/contribute/guidelines"
  files = ["! guidelines-adapters.md"]

# This file is automatically generated by tools/sync_tutorials.py
[[imports]]
path = "github.com/precice/tutorials"

  [[imports.mounts]]
  source = "aste-turbine/README.md"
  target = "content/tutorials/aste-turbine/_index.md"

  [[imports.mounts]]
  source = "aste-turbine/images"
  target = "content/tutorials/aste-turbine/images"

  [[imports.mounts]]
  source = "breaking-dam-2d/README.md"
  target = "content/tutorials/breaking-dam-2d/_index.md"

  [[imports.mounts]]
  source = "breaking-dam-2d/images"
  target = "content/tutorials/breaking-dam-2d/images"

  [[imports.mounts]]
  source = "channel-transport/README.md"
  target = "content/tutorials/channel-transport/_index.md"

  [[imports.mounts]]
  source = "channel-transport/images"
  target = "content/tutorials/channel-transport/images"

  [[imports.mounts]]
  source = "channel-transport-particles/README.md"
  target = "content/tutorials/channel-transport-particles/_index.md"

  [[imports.mounts]]
  source = "channel-transport-particles/images"
  target = "content/tutorials/channel-transport-particles/images"

  [[imports.mounts]]
  source = "channel-transport-reaction/README.md"
  target = "content/tutorials/channel-transport-reaction/_index.md"

  [[imports.mounts]]
  source = "channel-transport-reaction/images"
  target = "content/tutorials/channel-transport-reaction/images"

  [[imports.mounts]]
  source = "elastic-tube-1d/README.md"
  target = "content/tutorials/elastic-tube-1d/_index.md"

  [[imports.mounts]]
  source = "elastic-tube-1d/images"
  target = "content/tutorials/elastic-tube-1d/images"

  [[imports.mounts]]
  source = "elastic-tube-3d/README.md"
  target = "content/tutorials/elastic-tube-3d/_index.md"

  [[imports.mounts]]
  source = "elastic-tube-3d/images"
  target = "content/tutorials/elastic-tube-3d/images"

  [[imports.mounts]]
  source = "flow-around-controlled-moving-cylinder/README.md"
  target = "content/tutorials/flow-around-controlled-moving-cylinder/_index.md"

  [[imports.mounts]]
  source = "flow-around-controlled-moving-cylinder/images"
  target = "content/tutorials/flow-around-controlled-moving-cylinder/images"

  [[imports.mounts]]
  source = "flow-over-heated-plate/README.md"
  target = "content/tutorials/flow-over-heated-plate/_index.md"

  [[imports.mounts]]
  source = "flow-over-heated-plate/images"
  target = "content/tutorials/flow-over-heated-plate/images"

  [[imports.mounts]]
  source = "flow-over-heated-plate-nearest-projection/README.md"
  target = "content/tutorials/flow-over-heated-plate-nearest-projection/_index.md"

  [[imports.mounts]]
  source = "flow-over-heated-plate-nearest-projection/images"
  target = "content/tutorials/flow-over-heated-plate-nearest-projection/images"

  [[imports.mounts]]
  source = "flow-over-heated-plate-partitioned-flow/README.md"
  target = "content/tutorials/flow-over-heated-plate-partitioned-flow/_index.md"

  [[imports.mounts]]
  source = "flow-over-heated-plate-partitioned-flow/images"
  target = "content/tutorials/flow-over-heated-plate-partitioned-flow/images"

  [[imports.mounts]]
  source = "flow-over-heated-plate-steady-state/README.md"
  target = "content/tutorials/flow-over-heated-plate-steady-state/_index.md"

  [[imports.mounts]]
  source = "flow-over-heated-plate-steady-state/images"
  target = "content/tutorials/flow-over-heated-plate-steady-state/images"

  [[imports.mounts]]
  source = "flow-over-heated-plate-two-meshes/README.md"
  target = "content/tutorials/flow-over-heated-plate-two-meshes/_index.md"

  [[imports.mounts]]
  source = "flow-over-heated-plate-two-meshes/images"
  target = "content/tutorials/flow-over-heated-plate-two-meshes/images"

  [[imports.mounts]]
  source = "free-flow-over-porous-media/README.md"
  target = "content/tutorials/free-flow-over-porous-media/_index.md"

  [[imports.mounts]]
  source = "free-flow-over-porous-media/images"
  target = "content/tutorials/free-flow-over-porous-media/images"

  [[imports.mounts]]
  source = "heat-exchanger/README.md"
  target = "content/tutorials/heat-exchanger/_index.md"

  [[imports.mounts]]
  source = "heat-exchanger/images"
  target = "content/tutorials/heat-exchanger/images"

  [[imports.mounts]]
  source = "heat-exchanger-simplified/README.md"
  target = "content/tutorials/heat-exchanger-simplified/_index.md"

  [[imports.mounts]]
  source = "heat-exchanger-simplified/images"
  target = "content/tutorials/heat-exchanger-simplified/images"

  [[imports.mounts]]
  source = "multiple-perpendicular-flaps/README.md"
  target = "content/tutorials/multiple-perpendicular-flaps/_index.md"

  [[imports.mounts]]
  source = "multiple-perpendicular-flaps/images"
  target = "content/tutorials/multiple-perpendicular-flaps/images"

  [[imports.mounts]]
  source = "oscillator/README.md"
  target = "content/tutorials/oscillator/_index.md"

  [[imports.mounts]]
  source = "oscillator/images"
  target = "content/tutorials/oscillator/images"

  [[imports.mounts]]
  source = "oscillator-overlap/README.md"
  target = "content/tutorials/oscillator-overlap/_index.md"

  [[imports.mounts]]
  source = "oscillator-overlap/images"
  target = "content/tutorials/oscillator-overlap/images"

  [[imports.mounts]]
  source = "partitioned-backwards-facing-step/README.md"
  target = "content/tutorials/partitioned-backwards-facing-step/_index.md"

  [[imports.mounts]]
  source = "partitioned-backwards-facing-step/images"
  target = "content/tutorials/partitioned-backwards-facing-step/images"

  [[imports.mounts]]
  source = "partitioned-burgers-1d/README.md"
  target = "content/tutorials/partitioned-burgers-1d/_index.md"

  [[imports.mounts]]
  source = "partitioned-burgers-1d/images"
  target = "content/tutorials/partitioned-burgers-1d/images"

  [[imports.mounts]]
  source = "partitioned-elastic-beam/README.md"
  target = "content/tutorials/partitioned-elastic-beam/_index.md"

  [[imports.mounts]]
  source = "partitioned-elastic-beam/images"
  target = "content/tutorials/partitioned-elastic-beam/images"

  [[imports.mounts]]
  source = "partitioned-heat-conduction/README.md"
  target = "content/tutorials/partitioned-heat-conduction/_index.md"

  [[imports.mounts]]
  source = "partitioned-heat-conduction/images"
  target = "content/tutorials/partitioned-heat-conduction/images"

  [[imports.mounts]]
  source = "partitioned-heat-conduction-3d/README.md"
  target = "content/tutorials/partitioned-heat-conduction-3d/_index.md"

  [[imports.mounts]]
  source = "partitioned-heat-conduction-3d/images"
  target = "content/tutorials/partitioned-heat-conduction-3d/images"

  [[imports.mounts]]
  source = "partitioned-heat-conduction-complex/README.md"
  target = "content/tutorials/partitioned-heat-conduction-complex/_index.md"

  [[imports.mounts]]
  source = "partitioned-heat-conduction-complex/images"
  target = "content/tutorials/partitioned-heat-conduction-complex/images"

  [[imports.mounts]]
  source = "partitioned-heat-conduction-direct/README.md"
  target = "content/tutorials/partitioned-heat-conduction-direct/_index.md"

  [[imports.mounts]]
  source = "partitioned-heat-conduction-direct/images"
  target = "content/tutorials/partitioned-heat-conduction-direct/images"

  [[imports.mounts]]
  source = "partitioned-heat-conduction-overlap/README.md"
  target = "content/tutorials/partitioned-heat-conduction-overlap/_index.md"

  [[imports.mounts]]
  source = "partitioned-heat-conduction-overlap/images"
  target = "content/tutorials/partitioned-heat-conduction-overlap/images"

  [[imports.mounts]]
  source = "partitioned-pipe/README.md"
  target = "content/tutorials/partitioned-pipe/_index.md"

  [[imports.mounts]]
  source = "partitioned-pipe/images"
  target = "content/tutorials/partitioned-pipe/images"

  [[imports.mounts]]
  source = "partitioned-pipe-multiscale/README.md"
  target = "content/tutorials/partitioned-pipe-multiscale/_index.md"

  [[imports.mounts]]
  source = "partitioned-pipe-multiscale/images"
  target = "content/tutorials/partitioned-pipe-multiscale/images"

  [[imports.mounts]]
  source = "partitioned-pipe-two-phase/README.md"
  target = "content/tutorials/partitioned-pipe-two-phase/_index.md"

  [[imports.mounts]]
  source = "partitioned-pipe-two-phase/images"
  target = "content/tutorials/partitioned-pipe-two-phase/images"

  [[imports.mounts]]
  source = "perpendicular-flap/README.md"
  target = "content/tutorials/perpendicular-flap/_index.md"

  [[imports.mounts]]
  source = "perpendicular-flap/images"
  target = "content/tutorials/perpendicular-flap/images"

  [[imports.mounts]]
  source = "perpendicular-flap-stress/README.md"
  target = "content/tutorials/perpendicular-flap-stress/_index.md"

  [[imports.mounts]]
  source = "perpendicular-flap-stress/images"
  target = "content/tutorials/perpendicular-flap-stress/images"

  [[imports.mounts]]
  source = "quickstart/README.md"
  target = "content/tutorials/quickstart/_index.md"

  [[imports.mounts]]
  source = "quickstart/images"
  target = "content/tutorials/quickstart/images"

  [[imports.mounts]]
  source = "resonant-circuit/README.md"
  target = "content/tutorials/resonant-circuit/_index.md"

  [[imports.mounts]]
  source = "resonant-circuit/images"
  target = "content/tutorials/resonant-circuit/images"

  [[imports.mounts]]
  source = "turek-hron-fsi3/README.md"
  target = "content/tutorials/turek-hron-fsi3/_index.md"

  [[imports.mounts]]
  source = "turek-hron-fsi3/images"
  target = "content/tutorials/turek-hron-fsi3/images"

  [[imports.mounts]]
  source = "two-scale-heat-conduction/README.md"
  target = "content/tutorials/two-scale-heat-conduction/_index.md"

  [[imports.mounts]]
  source = "two-scale-heat-conduction/images"
  target = "content/tutorials/two-scale-heat-conduction/images"

  [[imports.mounts]]
  source = "volume-coupled-diffusion/README.md"
  target = "content/tutorials/volume-coupled-diffusion/_index.md"

  [[imports.mounts]]
  source = "volume-coupled-diffusion/images"
  target = "content/tutorials/volume-coupled-diffusion/images"

  [[imports.mounts]]
  source = "volume-coupled-flow/README.md"
  target = "content/tutorials/volume-coupled-flow/_index.md"

  [[imports.mounts]]
  source = "volume-coupled-flow/images"
  target = "content/tutorials/volume-coupled-flow/images"

  [[imports.mounts]]
  source = "water-hammer/README.md"
  target = "content/tutorials/water-hammer/_index.md"

  [[imports.mounts]]
  source = "water-hammer/images"
  target = "content/tutorials/water-hammer/images"

  [[imports.mounts]]
  source = "wolf-sheep-soil-creep/README.md"
  target = "content/tutorials/wolf-sheep-soil-creep/_index.md"

  [[imports.mounts]]
  source = "wolf-sheep-soil-creep/images"
  target = "content/tutorials/wolf-sheep-soil-creep/images"

  [[imports.mounts]]
  source = "tests/README.md"
  target = "content/docs/dev-docs/system-tests/_index.md"
