# Repository-specific edit links for local and mounted content.
github_editme_path = "https://github.com/precice/precice.github.io/edit/master/"

[github_editme_paths]
"content" = "https://github.com/precice/precice.github.io/edit/master/"
"github.com/precice/aste" = "https://github.com/precice/aste/edit/develop/"
"github.com/precice/calculix-adapter" = "https://github.com/precice/calculix-adapter/edit/develop/"
"github.com/precice/code_aster-adapter" = "https://github.com/precice/code_aster-adapter/edit/develop/"
"github.com/precice/dealii-adapter" = "https://github.com/precice/dealii-adapter/edit/develop/"
"github.com/precice/dumux-adapter" = "https://github.com/precice/dumux-adapter/edit/develop/"
"github.com/precice/dune-adapter" = "https://github.com/precice/dune-adapter/edit/main/"
"github.com/precice/fenics-adapter" = "https://github.com/precice/fenics-adapter/edit/develop/"
"github.com/precice/fenicsx-adapter" = "https://github.com/precice/fenicsx-adapter/edit/develop/"
"github.com/precice/fmi-runner" = "https://github.com/precice/fmi-runner/edit/main/"
"github.com/precice/micro-manager" = "https://github.com/precice/micro-manager/edit/develop/"
"github.com/precice/openfoam-adapter" = "https://github.com/precice/openfoam-adapter/edit/develop/"
"github.com/precice/preeco-orga" = "https://github.com/precice/preeco-orga/edit/main/"
"github.com/precice/su2-adapter" = "https://github.com/precice/su2-adapter/edit/develop/"
"github.com/precice/tutorials" = "https://github.com/precice/tutorials/edit/master/"
