repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        files: "^(README.md|pages/)"
      - id: markdownlint-fix
        files: "^(README.md|pages/)"
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
  - repo: local
    hooks:
      - id: check-api
        name: check old API use
        entry: tools/check-old-precice.py
        language: python
        types_or: [text]
        exclude: "^tools"
