baseURL = 'https://precice.org/'
languageCode = 'en-us'
title = 'preCICE - The Coupling Library'
theme = "precice"

[markup.goldmark.renderer]
unsafe = true

[module]

[[module.mounts]]
source = "images"
target = "assets/images"

[[module.mounts]]
source = "css"
target = "assets/css"

[[module.mounts]]
source = "_data"
target = "data"

[[module.mounts]]
source = "js"
target = "assets/js"
