name: Your story
description: Tell us your story and get it published on https://precice.org/community-projects.html
title: "[Sotry]: "
labels: ["content"]
assignees:
  - MakisH
body:
  - type: markdown
    attributes:
      value: |
        Your story is very important to us: apart from helping you advertise your work, it helps us argue in funding proposals and other occasions that preCICE is useful. And don't worry: it is already good enough, you can always update it later!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: Where can we contact you? This will be temporarily published in a GitHub issue, but not on the website.
      placeholder: ex. email@example.com
  - type: textarea
    id: description
    attributes:
      label: Your story
      description: In 1-2 paragraphs, describe your project
      placeholder: Motivated by X, we simulate Y. We couple solvers A and B with preCICE, and in particular use features foo and bar. Because of using preCICE, we were able to achieve many great goals.
  - type: input
    id: url
    attributes:
      label: More info
      description: Where can one read more? Ideally, a link to some paper / video / website / post on Discourse. You can always ask to update this later.
      placeholder: https://example.com/my-project
  - type: checkboxes
    id: image
    attributes:
      label: Image
      description: Remember to upload an image
      options:
        - label: I will upload an image to be published on the website directly after opening this issue, or send it via email to @MakisH.
          required: true
