destination: _site/
url: "http://127.0.0.1:4000"
baseurl: ""
port: 4000
output: pdf
product: docs
print_title: preCICE
print_subtitle: The coupling library for partitioned multi-physics simulations
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: docs_sidebar
