#!/usr/bin/env python3
"""Synchronize tutorial Hugo module mounts from precice/tutorials."""

import argparse
import logging
from pathlib import Path
import subprocess
import sys
import tempfile


def setup_logging() -> None:
    logging.basicConfig(
        level=logging.INFO,
        format="[%(levelname)s] %(message)s",
    )


def clone_tutorials(repo: str, branch: str | None, target_dir: Path) -> None:
    url = f"https://github.com/{repo}.git"
    cmd = ["git", "clone", "--depth=1"]
    if branch:
        cmd.extend(["--branch", branch])
    cmd.extend([url, str(target_dir)])

    branch_info = f"branch: {branch}" if branch else "default branch"
    logging.info(f"Cloning {url} ({branch_info}, depth: 1)...")
    try:
        subprocess.run(
            cmd,
            check=True,
            capture_output=True,
            text=True,
        )
    except subprocess.CalledProcessError as e:
        logging.error(f"Failed to clone {url}:\n{e.stderr}")
        sys.exit(1)


def discover_tutorials(tutorials_dir: Path) -> tuple[set[str], set[str]]:
    directories_with_readme: set[str] = set()
    directories_with_images: set[str] = set()

    for entry in tutorials_dir.iterdir():
        if not entry.is_dir() or entry.name.startswith("."):
            continue
        if entry.name in ("tools", "tests", "changelog-entries"):
            continue
        if (entry / "README.md").is_file():
            directories_with_readme.add(entry.name)
            if (entry / "images").is_dir():
                directories_with_images.add(f"{entry.name}/images")

    return directories_with_readme, directories_with_images


def generate_module_toml(
    toml_path: Path,
    tutorials: set[str],
    images: set[str],
    repo_path: str = "github.com/precice/tutorials",
) -> None:
    try:
        lines = toml_path.read_text(encoding="utf-8").splitlines()
    except Exception as e:
        logging.error(f"Failed to read existing toml file: {e}")
        sys.exit(1)

    marker = "# This file is automatically generated by tools/sync_tutorials.py"
    base_lines = []
    for line in lines:
        if marker in line:
            break
        base_lines.append(line.rstrip())

    while base_lines and not base_lines[-1].strip():
        base_lines.pop()
    base_lines.append("")

    toml_lines = base_lines + [
        marker,
        "[[imports]]",
        f'path = "{repo_path}"',
        "",
    ]

    for folder in sorted(tutorials):
        toml_lines.append("  [[imports.mounts]]")
        toml_lines.append(f'  source = "{folder}/README.md"')
        toml_lines.append(f'  target = "content/tutorials/{folder}/_index.md"')
        toml_lines.append("")

        if f"{folder}/images" in images:
            toml_lines.append("  [[imports.mounts]]")
            toml_lines.append(f'  source = "{folder}/images"')
            toml_lines.append(f'  target = "content/tutorials/{folder}/images"')
            toml_lines.append("")

    toml_lines.append("  [[imports.mounts]]")
    toml_lines.append('  source = "tests/README.md"')
    toml_lines.append('  target = "content/docs/dev-docs/system-tests/_index.md"')
    toml_lines.append("")

    try:
        toml_path.write_text("\n".join(toml_lines) + "\n", encoding="utf-8")
        logging.info(f"Updated {toml_path} with {len(tutorials)} tutorial mounts.")
    except Exception as e:
        logging.error(f"Failed to write toml file: {e}")
        sys.exit(1)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Synchronize tutorial Hugo module mounts from precice/tutorials."
    )
    parser.add_argument(
        "--module-toml",
        type=Path,
        default=Path("config/_default/module.toml"),
        help="Path to the module TOML file (default: config/_default/module.toml)",
    )
    parser.add_argument(
        "--repo",
        default="precice/tutorials",
        help="Target GitHub repository (default: precice/tutorials)",
    )
    parser.add_argument(
        "--branch",
        default=None,
        help="Target branch (default: clone default branch)",
    )
    parser.add_argument(
        "--local-repo",
        type=Path,
        default=None,
        help="Optional path to local clone of tutorials repo (bypasses shallow clone)",
    )

    args = parser.parse_args()
    setup_logging()

    if args.local_repo:
        tutorials_dir = args.local_repo.expanduser().resolve()
        if not tutorials_dir.is_dir():
            logging.error(f"Provided local repo is not a directory: {tutorials_dir}")
            sys.exit(1)
        tutorials, images = discover_tutorials(tutorials_dir)
    else:
        with tempfile.TemporaryDirectory() as temp_dir:
            clone_path = Path(temp_dir) / "tutorials"
            clone_tutorials(args.repo, args.branch, clone_path)
            tutorials, images = discover_tutorials(clone_path)

    generate_module_toml(args.module_toml, tutorials, images)


if __name__ == "__main__":
    main()
